### ISSUE TITLE
Twitter Api not working all the time

### ISSUE THREAD

**Issue by egowic** [xiaoyan-wang0/Msc-Group1-project#176]

**Comment by egowic** [comment]
@pinganzhang i believe there is no problem with the code that i wrote, you added some stuff to keep stuff in database i am almost sure that this is the reason why it is not working as it supposed to. Please have look at that, thank you.

**Comment by pinganzhang** [comment]
@egowic hey, you need to update your local database before, since I add new fields. And the problem is when I search for some things that do not exist, it return error.

**Comment by egowic** [comment]
@pinganzhang can you give an example that doesnt work for you so that i can test it
